// packages/aws-amplify-vue/src/components/api/graphql/Connect.vue
<template>
  <div>
    <template v-if="isMutation">
      <slot :loading="loading" :mutate="mutate" :errors="errors" />
    </template>
    <template v-else>
      <slot :loading="loading" :data="data" :errors="errors" />
    </template>
  </div>  
</template>

<script>

import Vue from 'vue';

export default {
  name: 'Connect',

  props: [
    'query',
    'mutation',
    'subscription',
    'onSubscriptionMsg',
  ],

  data () {
    return {
      logger: {},
      loading: false,
      data: {},
      errors: [],
      watchedSubscription: null,
      isMutation: false,
      internalMutation: null,
    }
  },

  watch: {
    query: function(val) {
      if (!this.loading) {
        this._fetchData();
      }
    },
    mutation: function(val) {
      if (!this.loading) {
        this._fetchData();
      }
    },
  },

  beforeMount() {
    this.logger = new this.$Amplify.Logger('Connect');
    this._fetchData();
  },

  beforeDestroy() {
    this._unsubscribe();
  },

  methods: {
    async mutate() {
      if (!this.isMutation) { return; }

      this.loading = true;
      await this.internalMutation();
      this.loading = false;
    },

    _setDefaultState() {
      this.loading = false;
      this.data = {};
      this.errors = [];
      this.isMutation = false;
      this.internalMutation = () => null;
    },

    async _fetchData() {
      const {
        query: { query = null, variables = {} } = {},
        mutation: { query: mutation = null, variables: mutationVariables = {} } = {},
        subscription,
        onSubscriptionMsg = (prevData) => prevData,
      } = this.$props;

      this._setDefaultState();

      if (!this.$Amplify.API || typeof this.$Amplify.API.graphql !== 'function' || typeof this.$Amplify.API.getGraphqlOperationType !== 'function') {
        throw new Error('No API module found, please ensure @aws-amplify/api is imported');
      }

      const hasValidQuery = query && this.$Amplify.API.getGraphqlOperationType(query) === 'query';
      const hasValidMutation = mutation && this.$Amplify.API.getGraphqlOperationType(mutation) === 'mutation';
      const hasValidSubscription = subscription && subscription.query
          && this.$Amplify.API.getGraphqlOperationType(subscription.query) === 'subscription';

      if (!hasValidQuery && !hasValidMutation && !hasValidSubscription) {
        this.logger.warn('No query, mutation, or subscription was specified');
      }

      if (hasValidQuery) {
        try {
          this.data = {};
          this.loading = true;
          const response = await this.$Amplify.API.graphql({ query, variables });
          this.data = response.data;
        } catch (error) {
          this.logger.warn(error);
          this.errors = error.errors;
          this.$emit('error', error);
        }
      }

      if (hasValidMutation) {
        this.isMutation = true;

        this.internalMutation = async () => {
          const result = await this.$Amplify.API.graphql({ query: mutation, variables: mutationVariables });
          this.$emit('done', result);
          return result;
        };
      }

      if (hasValidSubscription) {
        const { query: subscriptionQuery, variables: subscriptionVariables } = subscription;
        try {
          const observable = this.$Amplify.API.graphql({ query: subscriptionQuery, variables: subscriptionVariables });

          this.watchedSubscription = observable.subscribe({
            next: ({ value: { data }}) => {
              const prevData = {
                data: this.data,
                errors: this.errors,
                loading: this.loading,
              };
              this.data = onSubscriptionMsg(prevData, data);
            },
            error: (error) => this.logger.warn(error),
          });
        } catch (error) {
          this.errors = error.errors;
        }
      }

      this.loading = false;
    },

    _unsubscribe() {
      if (this.watchedSubscription) {
        this.watchedSubscription.unsubscribe();
      }
    },
  },
}
</script>

// packages/aws-amplify-react/src/API/GraphQL/Connect.js
import * as React from 'react';
import { API } from '@aws-amplify/api';

export class Connect extends React.Component {

    constructor(props) {
        super(props);

        this.state = this.getInitialState();
        this.subSubscription = null;
    }

    getInitialState() {
        const { query } = this.props;
        return {
            loading: query && !!query.query,
            data: {},
            errors: [],
            mutation: () => console.warn('Not implemented'),
        };
    }

    getDefaultState() {
        return {
            loading: false,
            data: {},
            errors: [],
            mutation: () => console.warn('Not implemented'),
        };
    }

    async _fetchData() {
        this._unsubscribe();
        this.setState({ loading: true });

        const {
            query: { query, variables = {} } = {},
            mutation: { query: mutation, mutationVariables = {} } = {},
            subscription,
            onSubscriptionMsg = (prevData) => prevData,
        } = this.props;

        let { data, mutation: mutationProp, errors } = this.getDefaultState();

        if (!API || typeof API.graphql !== 'function' || typeof API.getGraphqlOperationType !== 'function') {
            throw new Error('No API module found, please ensure @aws-amplify/api is imported');
        }

        const hasValidQuery = query && API.getGraphqlOperationType(query) === 'query';
        const hasValidMutation = mutation && API.getGraphqlOperationType(mutation) === 'mutation';
        const hasValidSubscription = subscription && API.getGraphqlOperationType(subscription.query) === 'subscription';

        if (!hasValidQuery && !hasValidMutation && !hasValidSubscription) {
            console.warn('No query, mutation or subscription was specified');
        }

        if (hasValidQuery) {
            try {
                data = null;

                const response = await API.graphql({ query, variables });

                data = response.data;
            } catch (err) {
                data = err.data;
                errors = err.errors;
            }
        }

        if (hasValidMutation) {
            mutationProp = async (variables) => {
                const result = await API.graphql({ query: mutation, variables });

                this.forceUpdate();
                return result;
            };
        }

        if (hasValidSubscription) {
            const { query: subsQuery, variables: subsVars } = subscription;

            try {
                const observable = API.graphql({ query: subsQuery, variables: subsVars });

                this.subSubscription = observable.subscribe({
                    next: ({ value: { data } }) => {
                        const { data: prevData } = this.state;
                        const newData = onSubscriptionMsg(prevData, data);
                        if (this.mounted) {
                            this.setState({ data: newData });
                        }
                    },
                    error: err => console.error(err),
                });
            } catch (err) {
                errors = err.errors;
            }
        }

        this.setState({ data, errors, mutation: mutationProp, loading: false });
    }

    _unsubscribe() {
        if (this.subSubscription) {
            this.subSubscription.unsubscribe();
        }
    }

    async componentDidMount() {
        this._fetchData();
        this.mounted = true;
    }

    componentWillUnmount() {
        this._unsubscribe();
        this.mounted = false;
    }

    componentDidUpdate(prevProps) {
        const { loading } = this.state;

        const { query: newQueryObj, mutation: newMutationObj } = this.props;
        const { query: prevQueryObj, mutation: prevMutationObj } = prevProps;

        // query
        const { query: newQuery, variables: newQueryVariables } = newQueryObj || {};
        const { query: prevQuery, variables: prevQueryVariables } = prevQueryObj || {};
        const queryChanged =
            prevQuery !== newQuery || JSON.stringify(prevQueryVariables) !== JSON.stringify(newQueryVariables);

        // mutation
        const { query: newMutation, variables: newMutationVariables } = newMutationObj || {};
        const { query: prevMutation, variables: prevMutationVariables } = prevMutationObj || {};
        const mutationChanged =
            prevMutation !== newMutation
            || JSON.stringify(prevMutationVariables) !== JSON.stringify(newMutationVariables);

        if (!loading && (queryChanged || mutationChanged)) {
            this._fetchData();
        }
    }

    render() {
        const { data, loading, mutation, errors } = this.state;
        return this.props.children({ data, errors, loading, mutation }) || null;
    }
}
