// packages/aws-amplify-vue/src/components/authenticator/SignUp.vue
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

<template>
  <div v-bind:class="amplifyUI.formSection" v-bind:data-test="auth.signUp.section">
    <div v-bind:class="amplifyUI.sectionHeader" v-bind:data-test="auth.signUp.headerSection">{{this.options.header}}</div>
    <div v-bind:class="amplifyUI.sectionBody" v-bind:data-test="auth.signUp.bodySection">
      <div v-bind:class="amplifyUI.formField"
          v-for="signUpField in this.orderedSignUpFields"
          :signUpField="signUpField.key"
          v-bind:key="signUpField.key"
        >
        <div v-bind:class="amplifyUI.inputLabel">{{signUpField.label}} {{signUpField.required ? '*': ''}}</div>
        <input
            v-if="signUpField.key !== 'phone_number'"
            :type = "signUpField.type"
            v-bind:class="[amplifyUI.input, signUpField.invalid ? 'invalid': '']"
            v-model="signUpField.value"
            :placeholder="signUpField.label"
            v-on:change="clear(signUpField)"
            v-bind:data-test="auth.signUp.nonPhoneNumberInput"
          />
        <div v-if="signUpField.key === 'phone_number'" v-bind:class="amplifyUI.selectInput">
          <select v-model="country" v-bind:data-test="auth.signUp.dialCodeSelect">
            <option v-for="country in countries" v-bind:key="country.label">{{country.label}}</option>
          </select>
          <input
            v-bind:class="[amplifyUI.input, signUpField.invalid ? 'invalid': '']"
            v-model="signUpField.value"
            type="number"
            :placeholder="signUpField.label"
            v-on:change="clear(signUpField)"
            v-bind:data-test="auth.signUp.phoneNumberInput"
          />
        </div>
      </div>
    </div>
    <div v-bind:class="amplifyUI.sectionFooter" v-bind:data-test="auth.signUp.footerSection">
      <span v-bind:class="amplifyUI.sectionFooterPrimaryContent">
        <button v-bind:class="amplifyUI.button" v-on:click="signUp" v-bind:data-test="auth.signUp.createAccountButton">{{$Amplify.I18n.get('Create Account')}}</button>
      </span>
      <span v-bind:class="amplifyUI.sectionFooterSecondaryContent">
        {{$Amplify.I18n.get('Have an account? ')}}
        <a v-bind:class="amplifyUI.a" v-on:click="signIn" v-bind:data-test="auth.signUp.signInLink">{{$Amplify.I18n.get('Sign in')}}</a>
      </span>
    </div>
    <div class="error" v-if="error">
      {{ error }}
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import Vue2Filters from 'vue2-filters'
import orderBy from 'lodash.orderby';
import AmplifyEventBus from '../../events/AmplifyEventBus';
import * as AmplifyUI from '@aws-amplify/ui';
import countries from '../../assets/countries';
import { auth } from '../../assets/data-test-attributes';

Vue.use(Vue2Filters)

export default {
  name: 'SignUp',
  props: ['signUpConfig'],
  data () {
    return {
      country: 'USA (+1)',
      countryCode: '1',
      countries,
      auth,
      amplifyUI: AmplifyUI,
      error: '',
      logger: {},
    }
  },
  computed: {
    options() {
      const defaults = {
        header: this.$Amplify.I18n.get('Create a new account'),
        signUpFields: [
          {
            label: this.$Amplify.I18n.get('Username'),
            key: 'username',
            required: true,
            type: 'text',
            displayOrder: 1,
          },
          {
            label: this.$Amplify.I18n.get('Password'),
            key: 'password',
            required: true,
            type: 'password',
            displayOrder: 2,
          },
          {
            label: this.$Amplify.I18n.get('Email'),
            key: 'email',
            required: true,
            type: 'text',
            displayOrder: 3
          },
          {
            label: this.$Amplify.I18n.get('Phone Number'),
            key: 'phone_number',
            required: true,
            displayOrder: 4
          }
        ]
      }

      // sets value in country code dropdown if defaultCountryCode value is present in props 
      if (this.signUpConfig && this.signUpConfig.defaultCountryCode) {
        this.country = this.countries.find(c => c.value === this.signUpConfig.defaultCountryCode).label;
      };

      if (this.signUpConfig && this.signUpConfig.hiddenDefaults && this.signUpConfig.hiddenDefaults.length > 0){
        defaults.signUpFields = defaults.signUpFields.filter((d) => {
          return !this.signUpConfig.hiddenDefaults.includes(d.key);
        });
      }

      // begin looping through signUpFields
      if (this.signUpConfig && this.signUpConfig.signUpFields && this.signUpConfig.signUpFields.length > 0) {
        // if hideAllDefaults and hideDefaults are not present on props...
        if (!this.signUpConfig.hideAllDefaults && !this.signUpConfig.hideDefaults) {
          // ...add default fields to signUpField array unless user has passed in custom field with matching key
          defaults.signUpFields.forEach((f, i) => {
            const matchKey = this.signUpConfig.signUpFields.findIndex((d) => {
              return d.key === f.key;
            });
            if (matchKey === -1) {
              this.signUpConfig.signUpFields.push(f);
            }
          });
        }
        /* 
          sort fields based on following rules:
          1. Fields with displayOrder are sorted before those without displayOrder
          2. Fields with conflicting displayOrder are sorted alphabetically by key
          3. Fields without displayOrder are sorted alphabetically by key
        */
        this.signUpConfig.signUpFields.sort((a, b) => {
          if (a.displayOrder && b.displayOrder) {
            if (a.displayOrder < b.displayOrder) {
              return -1;
            } else if (a.displayOrder > b.displayOrder) {
              return 1;
            } else {
              if (a.key < b.key) {
                return -1;
              } else {
                return 1;
              }
            }
          } else if (!a.displayOrder && b.displayOrder) {
            return -1;
          } else if (a.displayOrder && !b.displayOrder) {
            return 1;
          } else if (!a.displayOrder && !b.displayOrder) {
            if (a.key < b.key) {
              return 1;
            } else {
              return -1;
            }
          }
        });
      }
      
      return Object.assign(defaults, this.signUpConfig || {})
    },
    orderedSignUpFields: function () {
      return orderBy(this.options.signUpFields, 'displayOrder', 'name')
    }
  },
  mounted() {
    this.logger = new this.$Amplify.Logger(this.$options.name);
  },
  watch: {
    /*
    this operation is in place to avoid making country.value the select box
    bound key, which results in a duplicate key error in console
    */
    country: function() {
      this.countryCode = this.countries.find(c => c.label === this.country).value
    },
  },
  methods: {
    signUp: function() {
      if (!this.validate()) {
        return null;
      }

      let user = {
        attributes: {},
      };

      // puts field data into 'Auth.signUp' parameter structure
      this.options.signUpFields.forEach((e) => {
        if (e.key === 'username') {
          user.username = e.value
        } else if (e.key === 'password') {
          user.password = e.value
        } else if (e.key === 'phone_number' && e.value) {
          user.attributes.phone_number = `+${this.countryCode}${e.value}`
        } else {
          const newKey = `${this.needPrefix(e.key) ? 'custom:' : ''}${e.key}`;
          user.attributes[newKey] = e.value;
        };
      })

       this.$Amplify.Auth.signUp(user)
            .then(data => {
              this.logger.info('sign up success');
              AmplifyEventBus.$emit('localUser', data.user)
              if (data.userConfirmed === false){
                return AmplifyEventBus.$emit('authState', 'confirmSignUp');
              }
              return AmplifyEventBus.$emit('authState', 'signIn')
            })
            .catch(e => this.setError(e));

    },
    validate: function() {
      let invalids = [];
      this.options.signUpFields.map((el) => {
        if (el.required && !el.value) {
          invalids.push(el.label);
          Vue.set(el, 'invalid', true);
        }
        return el;
      })
      if (invalids.length > 0) {
        this.setError(`The following fields must be completed: ${invalids.join(', ')}`)
      }
      return invalids.length < 1;
    },
    signIn: function() {
      AmplifyEventBus.$emit('authState', 'signIn')
    },
    clear(field) {
      if (field && field.invalid && field.value) {
        Vue.set(field, 'invalid', false)
      }
    },
    setError: function(e) {
      this.error = this.$Amplify.I18n.get(e.message || e);
      this.logger.error(this.error)
    },

    // determines whether or not key needs to be prepended with 'custom:' for Cognito User Pool custom attributes.
    needPrefix: function(key) {
      const field = this.options.signUpFields.find(e => e.key === key);
      if (key.indexOf('custom:') !== 0) {
        return field.custom ;
      } else if (key.indexOf('custom:') === 0 && field.custom === false) {
          this.logger.warn('Custom prefix prepended to key but custom field flag is set to false');
      }
      return null;
    },
  }
}
</script>

// packages/aws-amplify-react/lib-esm/Auth/SignUp.js
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */
var __extends =
	(this && this.__extends) ||
	(function() {
		var extendStatics = function(d, b) {
			extendStatics =
				Object.setPrototypeOf ||
				({ __proto__: [] } instanceof Array &&
					function(d, b) {
						d.__proto__ = b;
					}) ||
				function(d, b) {
					for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
				};
			return extendStatics(d, b);
		};
		return function(d, b) {
			extendStatics(d, b);
			function __() {
				this.constructor = d;
			}
			d.prototype =
				b === null
					? Object.create(b)
					: ((__.prototype = b.prototype), new __());
		};
	})();
import * as React from 'react';
import { I18n, ConsoleLogger as Logger } from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import AuthPiece from './AuthPiece';
import {
	FormSection,
	SectionHeader,
	SectionBody,
	SectionFooter,
	FormField,
	Input,
	InputLabel,
	Button,
	Link,
	SectionFooterPrimaryContent,
	SectionFooterSecondaryContent,
} from '../Amplify-UI/Amplify-UI-Components-React';
import { auth } from '../Amplify-UI/data-test-attributes';
import countryDialCodes from './common/country-dial-codes';
import signUpWithUsernameFields, {
	signUpWithEmailFields,
	signUpWithPhoneNumberFields,
} from './common/default-sign-up-fields';
import { UsernameAttributes } from './common/types';
import { PhoneField } from './PhoneField';
var logger = new Logger('SignUp');
var SignUp = /** @class */ (function(_super) {
	__extends(SignUp, _super);
	function SignUp(props) {
		var _this = _super.call(this, props) || this;
		_this.state = { requestPending: false };
		_this._validAuthStates = ['signUp'];
		_this.signUp = _this.signUp.bind(_this);
		_this.sortFields = _this.sortFields.bind(_this);
		_this.getDefaultDialCode = _this.getDefaultDialCode.bind(_this);
		_this.checkCustomSignUpFields = _this.checkCustomSignUpFields.bind(_this);
		_this.needPrefix = _this.needPrefix.bind(_this);
		_this.header =
			_this.props && _this.props.signUpConfig && _this.props.signUpConfig.header
				? _this.props.signUpConfig.header
				: 'Create a new account';
		var _a = (_this.props || {}).usernameAttributes,
			usernameAttributes = _a === void 0 ? UsernameAttributes.USERNAME : _a;
		if (usernameAttributes === UsernameAttributes.EMAIL) {
			_this.defaultSignUpFields = signUpWithEmailFields;
		} else if (usernameAttributes === UsernameAttributes.PHONE_NUMBER) {
			_this.defaultSignUpFields = signUpWithPhoneNumberFields;
		} else {
			_this.defaultSignUpFields = signUpWithUsernameFields;
		}
		return _this;
	}
	SignUp.prototype.validate = function() {
		var _this = this;
		var invalids = [];
		this.signUpFields.map(function(el) {
			if (el.key !== 'phone_number') {
				if (el.required && !_this.inputs[el.key]) {
					el.invalid = true;
					invalids.push(el.label);
				} else {
					el.invalid = false;
				}
			} else {
				if (el.required && !_this.phone_number) {
					el.invalid = true;
					invalids.push(el.label);
				} else {
					el.invalid = false;
				}
			}
		});
		return invalids;
	};
	SignUp.prototype.sortFields = function() {
		var _this = this;
		if (
			this.props.signUpConfig &&
			this.props.signUpConfig.hiddenDefaults &&
			this.props.signUpConfig.hiddenDefaults.length > 0
		) {
			this.defaultSignUpFields = this.defaultSignUpFields.filter(function(d) {
				return !_this.props.signUpConfig.hiddenDefaults.includes(d.key);
			});
		}
		if (this.checkCustomSignUpFields()) {
			if (
				!this.props.signUpConfig ||
				!this.props.signUpConfig.hideAllDefaults
			) {
				// see if fields passed to component should override defaults
				this.defaultSignUpFields.forEach(function(f) {
					var matchKey = _this.signUpFields.findIndex(function(d) {
						return d.key === f.key;
					});
					if (matchKey === -1) {
						_this.signUpFields.push(f);
					}
				});
			}
			/*
            sort fields based on following rules:
            1. Fields with displayOrder are sorted before those without displayOrder
            2. Fields with conflicting displayOrder are sorted alphabetically by key
            3. Fields without displayOrder are sorted alphabetically by key
          */
			this.signUpFields.sort(function(a, b) {
				if (a.displayOrder && b.displayOrder) {
					if (a.displayOrder < b.displayOrder) {
						return -1;
					} else if (a.displayOrder > b.displayOrder) {
						return 1;
					} else {
						if (a.key < b.key) {
							return -1;
						} else {
							return 1;
						}
					}
				} else if (!a.displayOrder && b.displayOrder) {
					return 1;
				} else if (a.displayOrder && !b.displayOrder) {
					return -1;
				} else if (!a.displayOrder && !b.displayOrder) {
					if (a.key < b.key) {
						return -1;
					} else {
						return 1;
					}
				}
			});
		} else {
			this.signUpFields = this.defaultSignUpFields;
		}
	};
	SignUp.prototype.needPrefix = function(key) {
		var field = this.signUpFields.find(function(e) {
			return e.key === key;
		});
		if (key.indexOf('custom:') !== 0) {
			return field.custom;
		} else if (key.indexOf('custom:') === 0 && field.custom === false) {
			logger.warn(
				'Custom prefix prepended to key but custom field flag is set to false; retaining manually entered prefix'
			);
		}
		return null;
	};
	SignUp.prototype.getDefaultDialCode = function() {
		return this.props.signUpConfig &&
			this.props.signUpConfig.defaultCountryCode &&
			countryDialCodes.indexOf(
				'+' + this.props.signUpConfig.defaultCountryCode
			) !== -1
			? '+' + this.props.signUpConfig.defaultCountryCode
			: '+1';
	};
	SignUp.prototype.checkCustomSignUpFields = function() {
		return (
			this.props.signUpConfig &&
			this.props.signUpConfig.signUpFields &&
			this.props.signUpConfig.signUpFields.length > 0
		);
	};
	SignUp.prototype.signUp = function() {
		var _this = this;
		this.setState({ requestPending: true });
		if (!this.inputs.dial_code) {
			this.inputs.dial_code = this.getDefaultDialCode();
		}
		var validation = this.validate();
		if (validation && validation.length > 0) {
			this.setState({ requestPending: false });
			return this.error(
				'The following fields need to be filled out: ' + validation.join(', ')
			);
		}
		if (!Auth || typeof Auth.signUp !== 'function') {
			throw new Error(
				'No Auth module found, please ensure @aws-amplify/auth is imported'
			);
		}
		var signup_info = {
			username: this.inputs.username,
			password: this.inputs.password,
			attributes: {},
		};
		var inputKeys = Object.keys(this.inputs);
		var inputVals = Object.values(this.inputs);
		inputKeys.forEach(function(key, index) {
			if (
				!['username', 'password', 'checkedValue', 'dial_code'].includes(key)
			) {
				if (
					key !== 'phone_line_number' &&
					key !== 'dial_code' &&
					key !== 'error'
				) {
					var newKey = '' + (_this.needPrefix(key) ? 'custom:' : '') + key;
					signup_info.attributes[newKey] = inputVals[index];
				}
			}
		});
		if (this.phone_number)
			signup_info.attributes['phone_number'] = this.phone_number;
		var labelCheck = false;
		this.signUpFields.forEach(function(field) {
			if (field.label === _this.getUsernameLabel()) {
				logger.debug('Changing the username to the value of ' + field.label);
				signup_info.username =
					signup_info.attributes[field.key] || signup_info.username;
				labelCheck = true;
			}
		});
		if (!labelCheck && !signup_info.username) {
			// if the customer customized the username field in the sign up form
			// He needs to either set the key of that field to 'username'
			// Or make the label of the field the same as the 'usernameAttributes'
			throw new Error(
				"Couldn't find the label: " +
					this.getUsernameLabel() +
					', in sign up fields according to usernameAttributes!'
			);
		}
		Auth.signUp(signup_info)
			.then(function(data) {
				_this.setState({ requestPending: false });
				// @ts-ignore
				_this.changeState('confirmSignUp', data.user.username);
			})
			.catch(function(err) {
				_this.setState({ requestPending: false });
				return _this.error(err);
			});
	};
	SignUp.prototype.showComponent = function(theme) {
		var _this = this;
		var hide = this.props.hide;
		if (hide && hide.includes(SignUp)) {
			return null;
		}
		if (this.checkCustomSignUpFields()) {
			this.signUpFields = this.props.signUpConfig.signUpFields;
		}
		this.sortFields();
		return React.createElement(
			FormSection,
			{ theme: theme, 'data-test': auth.signUp.section },
			React.createElement(
				SectionHeader,
				{ theme: theme, 'data-test': auth.signUp.headerSection },
				I18n.get(this.header)
			),
			React.createElement(
				SectionBody,
				{ theme: theme, 'data-test': auth.signUp.bodySection },
				this.signUpFields.map(function(field) {
					return field.key !== 'phone_number'
						? React.createElement(
								FormField,
								{ theme: theme, key: field.key },
								field.required
									? React.createElement(
											InputLabel,
											{ theme: theme },
											I18n.get(field.label),
											' *'
									  )
									: React.createElement(
											InputLabel,
											{ theme: theme },
											I18n.get(field.label)
									  ),
								React.createElement(Input, {
									autoFocus:
										_this.signUpFields.findIndex(function(f) {
											return f.key === field.key;
										}) === 0
											? true
											: false,
									placeholder: I18n.get(field.placeholder),
									theme: theme,
									type: field.type,
									name: field.key,
									key: field.key,
									onChange: _this.handleInputChange,
									'data-test': auth.signUp.nonPhoneNumberInput,
								})
						  )
						: React.createElement(PhoneField, {
								theme: theme,
								required: field.required,
								defaultDialCode: _this.getDefaultDialCode(),
								label: field.label,
								placeholder: field.placeholder,
								onChangeText: _this.onPhoneNumberChanged,
								key: 'phone_number',
						  });
				})
			),
			React.createElement(
				SectionFooter,
				{ theme: theme, 'data-test': auth.signUp.footerSection },
				React.createElement(
					SectionFooterPrimaryContent,
					{ theme: theme },
					React.createElement(
						Button,
						{
							disabled: this.state.requestPending,
							onClick: this.signUp,
							theme: theme,
							'data-test': auth.signUp.createAccountButton,
						},
						I18n.get('Create Account')
					)
				),
				React.createElement(
					SectionFooterSecondaryContent,
					{ theme: theme },
					I18n.get('Have an account? '),
					React.createElement(
						Link,
						{
							theme: theme,
							onClick: function() {
								return _this.changeState('signIn');
							},
							'data-test': auth.signUp.signInLink,
						},
						I18n.get('Sign in')
					)
				)
			)
		);
	};
	return SignUp;
})(AuthPiece);
export default SignUp;
//# sourceMappingURL=SignUp.js.map
