// packages/aws-amplify-vue/src/components/storage/S3Album.vue
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

<template>
  <div>
    <div class="amplify-album">
      <div 
        class="amplify-album-container"
      >
        <amplify-s3-image
          class="amplify-image-container"
          v-for="item in items"
          v-bind:key="item.key"
          :imagePath="item.path"
        ></amplify-s3-image>
      </div>
    </div>
    <div class="error" v-if="error">
      {{ error }}
    </div>
  </div>
</template>

<script>
import AmplifyEventBus from '../../events/AmplifyEventBus';

export default {
  name: 'S3Album',
  props: ['path'],
  data () {
    return {
      logger: {},
      error: '',
      items: [],
    }
  },
  mounted() {
    this.logger = new this.$Amplify.Logger(this.$options.name);
    this.getImages();
    AmplifyEventBus.$on('fileUpload', img => {
      this.pushImage(img);
    });
  },
  methods: {
    getImages() {
      if (!this.path) { 
        setError('Album path not provided');
        return; 
      }
      const that = this;
      this.$Amplify.Storage.list(this.path)
        .then(res => {
          that.items = res.map(item => {
            return { path: item.key };
          });
        })
        .catch(e => this.setError(e));
    },
    pushImage(img) {
      if (!img) {
        setError('Image path not provided');
        return;
      }
      this.items.push({key: 123, path: img});
    },
    setError: function(e) {
      this.error = e.message || e;
      this.logger.error(this.error);
    }

  }
}
</script>

// packages/aws-amplify-react-native/src/Storage/S3Album.tsx
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

import React, { Component } from 'react';
import { ScrollView, Dimensions, StyleSheet } from 'react-native';
import { Storage, Logger } from 'aws-amplify';
import AmplifyTheme from '../AmplifyTheme';
import S3Image from './S3Image';

const logger = new Logger('Storage.S3Album');

export default class S3Album extends Component<any, any> {
	constructor(props) {
		super(props);

		this.state = { images: [] };
	}

	componentDidMount() {
		const { path, level, filter } = this.props;
		logger.debug(path);
		Storage.list(path, { level: level ? level : 'public' })
			.then(data => {
				logger.debug(data);
				if (filter) {
					data = filter(data);
				}
				this.setState({ images: data });
			})
			.catch(err => logger.warn(err));
	}

	render() {
		const { images } = this.state;
		if (!images) {
			return null;
		}

		const { width, height } = Dimensions.get('window');
		const theme = this.props.theme || AmplifyTheme;
		const albumStyle = Object.assign({}, StyleSheet.flatten(theme.album), {
			width: '100%',
			height: height,
		});
		const list = this.state.images.map(image => {
			return (
				<S3Image
					key={image.key}
					imgKey={image.key}
					resizeMode="cover"
					style={{ width: '100%', height: width }}
					theme={theme}
				/>
			);
		});
		return (
			<ScrollView {...this.props} style={albumStyle}>
				{list}
			</ScrollView>
		);
	}
}
