// packages/aws-amplify-vue/src/components/authenticator/ConfirmSignIn.vue
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

<template>
  <div v-bind:class="amplifyUI.formSection">
    <div v-bind:class="amplifyUI.sectionHeader">{{options.header}}</div>
    <div v-bind:class="amplifyUI.sectionBody">
      <div v-bind:class="amplifyUI.formField">
        <div v-bind:class="amplifyUI.inputLabel">{{$Amplify.I18n.get('Code')}} *</div>
        <input v-bind:class="amplifyUI.input" v-model="code" :placeholder="$Amplify.I18n.get('Code')" />
      </div>
    </div>
    <div v-bind:class="amplifyUI.sectionFooter">
      <span v-bind:class="amplifyUI.sectionFooterPrimaryContent">
        <button v-bind:class="amplifyUI.button" v-on:click="submit" :disabled="!code">{{$Amplify.I18n.get('Confirm')}}</button>
      </span>
      <span v-bind:class="amplifyUI.sectionFooterSecondaryContent">
        <a v-bind:class="amplifyUI.a" v-on:click="signIn">{{$Amplify.I18n.get('Back to Sign In')}}</a>      
      </span>
    </div>
    <div class="error" v-if="error">
      {{ error }}
    </div>
  </div>
</template>


<script>
import AmplifyEventBus from '../../events/AmplifyEventBus';
import * as AmplifyUI from '@aws-amplify/ui';

export default {
  name: 'ConfirmSignIn',
  props: ['confirmSignInConfig'],
  data () {
    return {
      verifyAttr: '',
      code: '',
      error: '',
      logger: {},
      amplifyUI: AmplifyUI
    }
  },
  computed: {
    options() {
      const defaults = {
        header: this.$Amplify.I18n.get('Confirm Sign In'),
        user: {},
      }
      return Object.assign(defaults, this.confirmSignInConfig || {})
    }
  },
  mounted() {
    this.logger = new this.$Amplify.Logger(this.$options.name);
    if (Object.keys(this.options.user).length === 0) {
      this.setError('Valid user not received.');
    };
  },
  methods: {
    submit: function() {
      this.$Amplify.Auth.confirmSignIn(this.options.user, this.code, this.options.user.challengeName)
        .then(() => {
          this.logger.info('confirmSignIn successs');
          AmplifyEventBus.$emit('authState', 'signedIn');
        })
        .catch(e => this.setError(e));
    },
    signIn: function() {
      AmplifyEventBus.$emit('authState', 'signedOut');
    },
    setError: function(e) {
      this.error = this.$Amplify.I18n.get(e.message || e);
      this.logger.error(this.error);
    }
  }
}
</script>

// packages/aws-amplify-react-native/src/components/auth/ConfirmSignIn.js
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

import React from 'react';
import { View, Text, TextInput, Button } from 'react-native';

//import Auth from '../../Auth';
//import I18n from '../../I18n';
//import { Logger } from '../../Common';

import {
    Auth,
    I18n,
    Logger
} from 'aws-amplify';

import AmplifyTheme from '../AmplifyTheme';
import { ConfirmationCode, LinkCell, Header, ErrorRow } from '../AmplifyUI';
import AuthPiece from './AuthPiece';

const logger = new Logger('SignIn');

const Footer = (props) => {
    const theme = props.theme || AmplifyTheme;
    return (
        <View style={theme.sectionFooter}>
            <LinkCell theme={theme} onPress={() => onStateChange('signIn')}>
                {I18n.get('Back to Sign In')}
            </LinkCell>
        </View>
    )
}

export default class ConfirmSignIn extends AuthPiece {
    constructor(props) {
        super(props);

        this.state = {
            code: null,
            error: null
        }

        this.confirm = this.confirm.bind(this);
    }

    confirm() {
        const user = this.props.authData;
        const { code } = this.state;
        logger.debug('Confirm Sign In for ' + user.username);
        Auth.confirmSignIn(user, code)
            .then(data => this.changeState('signedIn'))
            .catch(err => this.error(err));
    }

    render() {
        if (!['confirmSignIn'].includes(this.props.authState)) {
            return null;
        }

        const theme = this.props.theme || AmplifyTheme;
        return (
            <View style={theme.section}>
                <Header theme={theme}>{I18n.get('Confirm Sign In')}</Header>
                <View style={theme.sectionBody}>
                    <ConfirmationCode
                        theme={theme}
                        onChangeText={(text) => this.setState({ code: text })}
                    />
                    <Button
                        title={I18n.get('Confirm')}
                        onPress={this.confirm}
                        disabled={!this.state.code}
                    />
                </View>
                <Footer theme={theme} onStateChange={this.changeState}/>
                <ErrorRow theme={theme}>{this.state.error}</ErrorRow>
            </View>
        );
    }
}
