// packages/aws-amplify-react/src/Auth/ConfirmSignIn.tsx
/*
 * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

import * as React from 'react';

import { I18n, JS } from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';

import AuthPiece, { IAuthPieceProps, IAuthPieceState } from './AuthPiece';
import {
	FormSection,
	FormField,
	SectionHeader,
	SectionBody,
	SectionFooter,
	Input,
	InputLabel,
	Button,
	Link,
	SectionFooterPrimaryContent,
	SectionFooterSecondaryContent,
} from '../Amplify-UI/Amplify-UI-Components-React';

import { auth } from '../Amplify-UI/data-test-attributes';

export interface IConfirmSignInState extends IAuthPieceState {
	mfaType: string;
}

export default class ConfirmSignIn extends AuthPiece<
	IAuthPieceProps,
	IConfirmSignInState
> {
	constructor(props: IAuthPieceProps) {
		super(props);

		this._validAuthStates = ['confirmSignIn'];
		this.confirm = this.confirm.bind(this);
		this.checkContact = this.checkContact.bind(this);
		this.state = {
			mfaType: 'SMS',
		};
	}

	checkContact(user) {
		if (!Auth || typeof Auth.verifiedContact !== 'function') {
			throw new Error(
				'No Auth module found, please ensure @aws-amplify/auth is imported'
			);
		}

		Auth.verifiedContact(user).then(data => {
			if (!JS.isEmpty(data.verified)) {
				this.changeState('signedIn', user);
			} else {
				const newUser = Object.assign(user, data);
				this.changeState('verifyContact', newUser);
			}
		});
	}

	confirm(event) {
		if (event) {
			event.preventDefault();
		}
		const user = this.props.authData;
		const { code } = this.inputs;
		const mfaType =
			user.challengeName === 'SOFTWARE_TOKEN_MFA' ? 'SOFTWARE_TOKEN_MFA' : null;
		if (!Auth || typeof Auth.confirmSignIn !== 'function') {
			throw new Error(
				'No Auth module found, please ensure @aws-amplify/auth is imported'
			);
		}

		Auth.confirmSignIn(user, code, mfaType)
			.then(() => {
				this.checkContact(user);
			})
			.catch(err => this.error(err));
	}

	componentDidUpdate() {
		// logger.debug('component did update with props', this.props);
		const user = this.props.authData;
		const mfaType =
			user && user.challengeName === 'SOFTWARE_TOKEN_MFA' ? 'TOTP' : 'SMS';
		if (this.state.mfaType !== mfaType) this.setState({ mfaType });
	}

	showComponent(theme) {
		const { hide } = this.props;
		if (hide && hide.includes(ConfirmSignIn)) {
			return null;
		}

		return (
			<FormSection theme={theme} data-test={auth.confirmSignIn.section}>
				<SectionHeader
					theme={theme}
					data-test={auth.confirmSignIn.headerSection}
				>
					{I18n.get('Confirm ' + this.state.mfaType + ' Code')}
				</SectionHeader>
				<form
					onSubmit={this.confirm}
					data-test={auth.confirmSignIn.bodySection}
				>
					<SectionBody theme={theme}>
						<FormField theme={theme}>
							<InputLabel theme={theme}>{I18n.get('Code')} *</InputLabel>
							<Input
								autoFocus
								placeholder={I18n.get('Code')}
								theme={theme}
								key="code"
								name="code"
								autoComplete="off"
								onChange={this.handleInputChange}
								data-test={auth.confirmSignIn.codeInput}
							/>
						</FormField>
					</SectionBody>
					<SectionFooter theme={theme}>
						<SectionFooterPrimaryContent
							theme={theme}
							data-test={auth.confirmSignIn.confirmButton}
						>
							<Button theme={theme} type="submit">
								{I18n.get('Confirm')}
							</Button>
						</SectionFooterPrimaryContent>
						<SectionFooterSecondaryContent theme={theme}>
							<Link
								theme={theme}
								onClick={() => this.changeState('signIn')}
								data-test={auth.confirmSignIn.backToSignInLink}
							>
								{I18n.get('Back to Sign In')}
							</Link>
						</SectionFooterSecondaryContent>
					</SectionFooter>
				</form>
			</FormSection>
		);
	}
}

// packages/aws-amplify-vue/src/components/authenticator/ConfirmSignIn.vue
/* * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights
Reserved. * * Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with * the License. A copy of the
License is located at * * http://aws.amazon.com/apache2.0/ * * or in the
"license" file accompanying this file. This file is distributed on an "AS IS"
BASIS, WITHOUT WARRANTIES OR * CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing permissions * and
limitations under the License. */

<template>
	<div
		v-bind:class="amplifyUI.formSection"
		v-bind:data-test="auth.confirmSignIn.section"
	>
		<div
			v-bind:class="amplifyUI.sectionHeader"
			v-bind:data-test="auth.confirmSignIn.headerSection"
		>
			{{ options.header }}
		</div>
		<div
			v-bind:class="amplifyUI.sectionBody"
			v-bind:data-test="auth.confirmSignIn.bodySection"
		>
			<div v-bind:class="amplifyUI.formField">
				<div v-bind:class="amplifyUI.inputLabel">
					{{ $Amplify.I18n.get('Code') }} *
				</div>
				<input
					v-bind:class="amplifyUI.input"
					v-model="code"
					:placeholder="$Amplify.I18n.get('Code')"
					v-bind:data-test="auth.confirmSignIn.codeInput"
				/>
			</div>
		</div>
		<div v-bind:class="amplifyUI.sectionFooter">
			<span v-bind:class="amplifyUI.sectionFooterPrimaryContent">
				<button
					v-bind:class="amplifyUI.button"
					v-on:click="submit"
					:disabled="!code"
					v-bind:data-test="auth.confirmSignIn.confirmButton"
				>
					{{ $Amplify.I18n.get('Confirm') }}
				</button>
			</span>
			<span v-bind:class="amplifyUI.sectionFooterSecondaryContent">
				<a
					v-bind:class="amplifyUI.a"
					v-on:click="signIn"
					v-bind:data-test="auth.confirmSignIn.backToSignInLink"
					>{{ $Amplify.I18n.get('Back to Sign In') }}</a
				>
			</span>
		</div>
		<div class="error" v-if="error">
			{{ error }}
		</div>
	</div>
</template>

<script>
import AmplifyEventBus from '../../events/AmplifyEventBus';
import * as AmplifyUI from '@aws-amplify/ui';
import { auth } from '../../assets/data-test-attributes';

export default {
	name: 'ConfirmSignIn',
	props: ['confirmSignInConfig'],
	data() {
		return {
			verifyAttr: '',
			code: '',
			error: '',
			logger: {},
			amplifyUI: AmplifyUI,
			auth,
		};
	},
	computed: {
		options() {
			const defaults = {
				header: this.$Amplify.I18n.get('Confirm Sign In'),
				user: {},
			};
			return Object.assign(defaults, this.confirmSignInConfig || {});
		},
	},
	mounted() {
		this.logger = new this.$Amplify.Logger(this.$options.name);
		if (Object.keys(this.options.user).length === 0) {
			this.setError('Valid user not received.');
		}
	},
	methods: {
		submit: function () {
			this.$Amplify.Auth.confirmSignIn(
				this.options.user,
				this.code,
				this.options.user.challengeName
			)
				.then(() => {
					this.logger.info('confirmSignIn successs');
					AmplifyEventBus.$emit('authState', 'signedIn');
				})
				.catch((e) => this.setError(e));
		},
		signIn: function () {
			AmplifyEventBus.$emit('authState', 'signIn');
		},
		setError: function (e) {
			this.error = this.$Amplify.I18n.get(e.message || e);
			this.logger.error(this.error);
		},
	},
};
</script>
